"""Render a complete, self-contained, scientifically rigorous HTML report for SemAdExp.

Reads results/pipeline_summary.json (generated by `run-all --scale full`), embeds all
figures as base64 PNGs, and writes docs/semadexp_report.html.

Usage: python scripts/render_html_report.py [--summary results/pipeline_summary.json]
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

os.environ.setdefault("MPLCONFIGDIR", os.path.join(tempfile.gettempdir(), "semadexp_mplcache"))

import matplotlib

matplotlib.use("Agg")
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

mpl.rcParams["font.sans-serif"] = [
    "Arial Unicode MS",
    "Heiti SC",
    "Hiragino Sans GB",
    "PingFang SC",
    "Songti SC",
]
mpl.rcParams["axes.unicode_minus"] = False


def _fmt(x, nd: int = 3) -> str:
    if x is None:
        return "—"
    try:
        return f"{float(x):.{nd}f}"
    except (TypeError, ValueError):
        return str(x)


def _pct(x, nd: int = 1) -> str:
    if x is None:
        return "—"
    return f"{float(x) * 100:.{nd}f}%"


def _b64(path: Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("ascii")


def _img(path: Path, caption: str, width: str = "92%") -> str:
    return (
        f'<figure><img src="data:image/png;base64,{_b64(path)}" style="width:{width};" '
        f'alt="{caption}"/><figcaption>{caption}</figcaption></figure>'
    )


def _table(headers: list[str], rows: list[list[str]], cls: str = "") -> str:
    thead = "".join(f"<th>{h}</th>" for h in headers)
    body = "".join(
        "<tr>" + "".join(f"<td>{c}</td>" for c in row) + "</tr>" for row in rows
    )
    return f'<table class="{cls}"><thead><tr>{thead}</tr></thead><tbody>{body}</tbody></table>'


def _chip(label: str, value: str, tone: str = "blue") -> str:
    return f'<div class="chip chip-{tone}"><div class="chip-label">{label}</div><div class="chip-value">{value}</div></div>'


def _fig_ablation(s: dict, out: Path) -> Path:
    labels = ["传统行为特征", "融合 LLM 语义特征"]
    auc = [s["auc_trad"], s["auc_fused"]]
    ll = [s["logloss_trad"], s["logloss_fused"]]
    fig, axes = plt.subplots(1, 2, figsize=(9.5, 3.8))
    axes[0].bar(labels, auc, color=["#8fa8c8", "#1f6feb"], width=0.5)
    axes[0].set_title("AUC（5 折交叉验证）")
    axes[0].set_ylim(0.5, 0.8)
    for i, v in enumerate(auc):
        axes[0].text(i, v + 0.005, f"{v:.4f}", ha="center", fontsize=9)
    axes[1].bar(labels, ll, color=["#8fa8c8", "#1f6feb"], width=0.5)
    axes[1].set_title("对数损失（越低越好）")
    for i, v in enumerate(ll):
        axes[1].text(i, v + 0.005, f"{v:.4f}", ha="center", fontsize=9)
    fig.suptitle(
        f"语义增量信息：AUC {s['auc_trad']:.4f} → {s['auc_fused']:.4f}（+{s['auc_gain']:.4f}），"
        f"熵增益 +{s['entropy_gain']:.4f} nats"
    )
    fig.tight_layout()
    p = out / "fig_ablation.png"
    fig.savefig(p, dpi=150)
    plt.close(fig)
    return p


def _fig_design(design_rows: list[dict], out: Path) -> Path:
    policies = ["structured_stratified", "semantic_stratified", "graph_cluster"]
    short = {"structured_stratified": "结构化分层", "semantic_stratified": "语义分层", "graph_cluster": "竞争图谱群落"}
    edge, smd = [], []
    for p in policies:
        rows = [r for r in design_rows if r["bucketing"] == p]
        edge.append(float(np.mean([r["cross_arm_edge_ratio"] for r in rows])))
        smd.append(float(np.mean([r["max_smd"] for r in rows])))
    x = np.arange(len(policies))
    fig, ax = plt.subplots(figsize=(8, 3.8))
    ax.bar(x - 0.18, edge, 0.36, label="跨组强竞争边占比（越低越好）", color="#1f6feb")
    ax.bar(x + 0.18, smd, 0.36, label="最大 SMD（协变量平衡，越低越好）", color="#f2a03d")
    ax.set_xticks(x)
    ax.set_xticklabels([short[p] for p in policies])
    ax.set_ylim(0, 1.6)
    for xi, (e, s) in enumerate(zip(edge, smd)):
        ax.text(xi - 0.18, e + 0.03, f"{e:.3f}", ha="center", fontsize=9)
        ax.text(xi + 0.18, s + 0.03, f"{s:.3f}", ha="center", fontsize=9)
    ax.legend(fontsize=8)
    ax.set_title("分桶策略设计指标：竞争隔离 vs 协变量平衡")
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    p = out / "fig_design.png"
    fig.savefig(p, dpi=150)
    plt.close(fig)
    return p


def _fig_bias_rmse(results_rows: list[dict], out: Path) -> Path:
    policies = ["structured_stratified", "semantic_stratified", "graph_cluster"]
    short = {"structured_stratified": "结构化分层", "semantic_stratified": "语义分层", "graph_cluster": "竞争图谱群落"}
    bias, rmse, var = [], [], []
    for p in policies:
        rows = [r for r in results_rows if r["bucketing"] == p]
        bias.append(float(np.mean([r["bias"] for r in rows])))
        rmse.append(float(np.mean([r["rmse"] for r in rows])))
        var.append(float(np.mean([r["variance"] for r in rows])))
    x = np.arange(len(policies))
    fig, ax = plt.subplots(figsize=(8, 3.8))
    ax.bar(x - 0.2, bias, 0.4, label="bias（全部场景×估计器平均）", color="#e5534b")
    ax.bar(x + 0.2, rmse, 0.4, label="RMSE", color="#1f6feb")
    ax.axhline(0, color="gray", lw=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels([short[p] for p in policies])
    for xi, (b, r) in enumerate(zip(bias, rmse)):
        ax.text(xi - 0.2, b - 0.08, f"{b:.2f}", ha="center", fontsize=9, color="white")
        ax.text(xi + 0.2, r + 0.03, f"{r:.2f}", ha="center", fontsize=9)
    ax.legend(fontsize=8)
    ax.set_title("估计准确性：bias / RMSE 随分桶策略变化")
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    p = out / "fig_bias_rmse.png"
    fig.savefig(p, dpi=150)
    plt.close(fig)
    return p


def _render(summary: dict, results_dir: Path, out_path: Path) -> Path:
    meta = summary.get("meta", {})
    abl = summary.get("ablation", {})
    matrix = summary.get("matrix", {})
    results_rows = matrix.get("results", [])
    design_rows = matrix.get("design", [])
    he = summary.get("hypothesis_eval", {})
    ranked = summary.get("ranked_hypotheses", [])
    eq = summary.get("equilibrium", {})
    loop = summary.get("closed_loop", {})

    tmp = out_path.parent / ".html_figs"
    tmp.mkdir(parents=True, exist_ok=True)
    fig_dir = results_dir / "figures"
    figs = {
        "graph": _img(fig_dir / "fig_graph.png", "图 1 · LLM 语义竞争图谱（节点=广告主，颜色=竞争群落）"),
        "rmse": _img(fig_dir / "fig_matrix_rmse.png", "图 2 · 分桶 × 估计器 RMSE 对比"),
        "capture": _img(fig_dir / "fig_capture_curve.png", "图 3 · 假设生成的 Top-K 价值捕获曲线"),
        "sensitivity": _img(fig_dir / "fig_sensitivity.png", "图 4 · 反事实均衡模拟灵敏度分析"),
        "attribution": _img(fig_dir / "fig_attribution.png", "图 5 · 异质性效应的语义分群估计（CATE）"),
        "ablation": _img(_fig_ablation(abl, tmp), "图 6 · LLM 语义增量信息：AUC 与对数损失"),
        "design": _img(_fig_design(design_rows, tmp), "图 7 · 分桶策略设计指标：竞争隔离 vs 协变量平衡"),
        "bias_rmse": _img(_fig_bias_rmse(results_rows, tmp), "图 8 · bias / RMSE 随分桶策略变化"),
    }

    # ---- aggregated tables -------------------------------------------------
    policies_cn = {
        "structured_stratified": "结构化分层",
        "semantic_stratified": "语义分层",
        "graph_cluster": "竞争图谱群落",
    }
    est_cn = {
        "diff_in_means": "朴素差分",
        "cuped": "CUPED",
        "randomization_inference": "随机化推断",
        "exposure_mapping": "暴露映射",
    }
    worst_rows = [r for r in results_rows if r["scenario"] == "高干扰-高异质性"]
    structured_edge = next(
        (r["cross_arm_edge_ratio"] for r in design_rows if r["bucketing"] == "structured_stratified"),
        0.0,
    )
    graph_edge = min(
        (r["cross_arm_edge_ratio"] for r in design_rows if r["bucketing"] == "graph_cluster"),
        default=0.0,
    )
    graph_rmse = min(
        (
            r["rmse"]
            for r in worst_rows
            if r["bucketing"] == "graph_cluster" and r["estimator"] == "diff_in_means"
        ),
        default=0.0,
    )
    worst_tbl = _table(
        ["分桶策略", "估计器", "bias", "方差", "RMSE", "覆盖率", "功效"],
        [
            [
                policies_cn.get(r["bucketing"], r["bucketing"]),
                est_cn.get(r["estimator"], r["estimator"]),
                _fmt(r["bias"]),
                _fmt(r["variance"], 4),
                _fmt(r["rmse"]),
                _fmt(r["coverage"]),
                _fmt(r["power"]),
            ]
            for r in worst_rows
        ],
        "data",
    )
    agg: dict[tuple[str, str], dict] = {}
    for r in results_rows:
        key = (r["bucketing"], r["estimator"])
        a = agg.setdefault(key, {"bias": [], "variance": [], "rmse": [], "coverage": [], "power": []})
        for k in a:
            a[k].append(r[k])
    overall_tbl = _table(
        ["分桶策略", "估计器", "bias", "方差", "RMSE", "覆盖率", "功效"],
        [
            [
                policies_cn.get(k[0], k[0]),
                est_cn.get(k[1], k[1]),
                _fmt(float(np.mean(v["bias"]))),
                _fmt(float(np.mean(v["variance"])), 4),
                _fmt(float(np.mean(v["rmse"]))),
                _fmt(float(np.mean(v["coverage"]))),
                _fmt(float(np.mean(v["power"]))),
            ]
            for k, v in sorted(agg.items())
        ],
        "data",
    )
    design_tbl = _table(
        ["场景", "分桶策略", "最大 SMD", "跨组强竞争边占比", "社区内边密度"],
        [
            [
                r["scenario"],
                policies_cn.get(r["bucketing"], r["bucketing"]),
                _fmt(r["max_smd"]),
                _fmt(r["cross_arm_edge_ratio"]),
                _fmt(r["internal_density"]),
            ]
            for r in design_rows
        ],
        "data",
    )
    cap_tbl = _table(
        ["已开展实验数 K", "LLM 优先级排序捕获", "随机基线", "人工盲选基线"],
        [
            [k, _pct(v), _pct(he.get("random_baseline_capture", {}).get(k)), _pct(he.get("manual_baseline_capture", {}).get(k))]
            for k, v in sorted(he.get("top_k_capture", {}).items(), key=lambda kv: int(kv[0]))
        ],
        "data",
    )
    ranked_tbl = _table(
        ["优先级", "假设陈述", "指标", "方向", "置信度", "预期收益", "风险", "匹配实验", "真实效应"],
        [
            [
                _fmt(h.get("priority")),
                h.get("statement", ""),
                h.get("metric", ""),
                "↑" if h.get("direction") == "up" else "↓",
                _fmt(h.get("confidence")),
                _fmt(h.get("expected_lift")),
                _fmt(h.get("risk")),
                str(h.get("matched_experiment_id") or "—"),
                _fmt(h.get("true_effect")),
            ]
            for h in ranked
        ],
        "data",
    )
    eq_tbl = _table(
        ["生态指标", "动态均衡（含广告主响应）", "静态（忽略响应）"],
        [
            [
                k,
                _fmt(eq.get("final_metrics", {}).get(k)),
                _fmt(eq.get("static_metrics", {}).get(k)),
            ]
            for k in (eq.get("final_metrics") or {})
        ],
        "data",
    )
    sens_tbl = _table(
        ["响应幅度扰动", "总消耗", "总转化", "负反馈率", "广告主留存", "中小广告主存活率"],
        [
            [
                f"{r.get('magnitude_multiplier', '')}×",
                _fmt(r.get("total_spend")),
                _fmt(r.get("total_conversions"), 0),
                _fmt(r.get("negative_feedback_rate"), 4),
                _fmt(r.get("advertiser_survival")),
                _fmt(r.get("small_advertiser_survival")),
            ]
            for r in eq.get("sensitivity", [])
        ],
        "data",
    )
    est_tbl = _table(
        ["估计器", "点估计", "标准误", "95% CI 下限", "95% CI 上限", "p 值"],
        [
            [
                est_cn.get(r.get("estimator"), r.get("estimator")),
                _fmt(r.get("estimate")),
                _fmt(r.get("se")),
                _fmt(r.get("ci_low")),
                _fmt(r.get("ci_high")),
                _fmt(r.get("p_value"), 4),
            ]
            for r in loop.get("estimates", [])
        ],
        "data",
    )

    body = f"""
<header class="hero">
  <div class="hero-inner">
    <div class="kicker">SemAdExp · 技术可视化报告</div>
    <h1>LLM 语义增强的双边市场实验智能平台</h1>
    <p class="subtitle">假设生成 → 反事实均衡仿真 → 语义竞争分桶 → 效果估计 → 归因与剥离 → 知识回流
    <span class="muted">｜四层全部量化验证｜固定种子可复现</span></p>
    <div class="meta">
      <span>数据规模：{meta.get('scale', 'full')}（场景矩阵 {len({r['scenario'] for r in results_rows})} 个场景 × 3 分桶 × 4 估计器 × 重复实验）</span>
      <span>随机种子：{meta.get('seed', 7)}</span>
      <span>生成时间：{meta.get('generated_at', '—')}</span>
    </div>
  </div>
</header>

<nav id="toc"><div class="toc-title">目录</div>
  <a href="#s1">1 摘要与核心结论</a>
  <a href="#s2">2 研究问题与贡献</a>
  <a href="#s3">3 平台架构</a>
  <a href="#s4">4 数据与 LLM 语义层</a>
  <a href="#s5">5 仿真器与真值构建</a>
  <a href="#s6">6 实验设计：竞争图谱分桶</a>
  <a href="#s7">7 效果评估：准确性证据</a>
  <a href="#s8">8 效应剥离与异质性归因</a>
  <a href="#s9">9 反事实均衡模拟</a>
  <a href="#s10">10 假设生成与排序</a>
  <a href="#s11">11 闭环演示</a>
  <a href="#s12">12 复现与工程保障</a>
  <a href="#s13">13 局限性与结论</a>
  <a href="#s14">附录 指标定义</a>
</nav>

<main>
<section id="s1">
  <h2>1　摘要与核心结论</h2>
  <div class="chips">
    {_chip("语义增量信息", f"AUC {abl.get('auc_trad', 0):.4f} → {abl.get('auc_fused', 0):.4f}（+{abl.get('auc_gain', 0):.4f}）")}
    {_chip("竞争隔离", f"跨组强竞争边 {structured_edge:.3f} → {graph_edge:.3f}", "green")}
    {_chip("估计准确性", f"最严苛场景 RMSE {graph_rmse:.3f}")}
    {_chip("迭代效率", f"{he.get('experiments_to_50pct', '—')} 个实验达 50% 价值捕获（随机基线 {he.get('random_experiments_to_50pct', '—')} 个）", "orange")}
  </div>
  <p>本报告围绕一个核心命题：<strong>广告平台的双边市场特性使实验面临跨侧干扰与广告主异质性，传统统计方法难以准确衡量策略效果；将 LLM 语义信息贯穿实验全链路可以显著提升衡量的准确性、稳定性与迭代效率。</strong></p>
  <p>所有结论均来自固定随机种子下的可复现运行（full 规模），数值与代码仓库中的 `results/` 产物完全一致；方法、假设与局限性在报告中如实披露。</p>
</section>

<section id="s2">
  <h2>2　研究问题与贡献</h2>
  <div class="card-grid">
    <div class="card"><h3>挑战 1 · 衡量准确性</h3><p>跨组预算挤占与流量转移使实验效果并非策略本身的效果；传统置信区间在干扰下大面积失准（覆盖率最低 0.0–0.1）。</p></div>
    <div class="card"><h3>挑战 2 · 广告主异质性</h3><p>传统按预算/行业分层无法捕捉细粒度竞争关系，采样稳定性受强竞争广告主跨组分流影响。</p></div>
    <div class="card"><h3>挑战 3 · 特征滞后</h3><p>结构化行为特征维度有限；广告文案、操作日志等非结构化数据蕴含大量未被利用的语义增量信息。</p></div>
    <div class="card"><h3>挑战 4 · 迭代效率</h3><p>人工驱动假设受经验盲区限制；缺少量化的实验优先级排序，高成本低收益实验频发。</p></div>
  </div>
  <p><strong>本平台的贡献</strong>：构建闭环系统，将 LLM 语义能力应用于（a）从非结构化语料生成可验证实验假设并量化排序；（b）生成广告主策略响应假设驱动反事实均衡模拟；（c）构建广告主竞争语义图谱实现竞争感知分桶；（d）驱动预测增强估计、异质性归因与内生干扰剥离。四个层级的增益均有真值对照下的量化证据。</p>
</section>

<section id="s3">
  <h2>3　平台架构</h2>
  <div class="arch">
    <div class="arch-box arch-top">非结构化语料：工单 · 用户负反馈 · 审核记录 · 实验复盘 · 行业动态</div>
    <div class="arch-arrow">↓</div>
    <div class="arch-box arch-up">实验上游层：LLM 假设提取 → 语义去重 → 可行性过滤 → 优先级 = 预期收益 × 置信度 / 风险</div>
    <div class="arch-arrow">↓</div>
    <div class="arch-box arch-sim">前置仿真层：双边市场仿真器 + LLM 广告主响应假设 + 均衡迭代（含流失）+ 灵敏度带</div>
    <div class="arch-arrow">↓</div>
    <div class="arch-box arch-des">实验设计层：语义竞争图谱 → Louvain 群落 → 群落随机化分桶 / 语义分层 / 结构化分层</div>
    <div class="arch-arrow">↓</div>
    <div class="arch-box arch-est">效果评估层：差分 · CUPED · 随机化推断 · 暴露映射 ＋ 效应剥离 ＋ 语义归因</div>
    <div class="arch-arrow arch-loop">↺ 知识回流（估计/归因结果更新历史知识库）</div>
  </div>
  <p class="muted">支撑层：OpenAI 双后端语义提取（离线确定性后端等价）· 哈希缓存 · 行为数据基线（可替换 Criteo）· 固定种子语料生成。</p>
</section>

<section id="s4">
  <h2>4　数据与 LLM 语义层</h2>
  <p>全部语料由固定种子受控生成（广告文案 8 品类、操作日志、工单、复盘文档），行为基线默认离线合成、可替换 Criteo。LLM 双后端保证：设置 <code>OPENAI_API_KEY</code> 后使用 <code>gpt-4o-mini</code> + <code>text-embedding-3-small</code>；未设置时确定性离线后端输出等价 JSON 契约。全部输出按 prompt 哈希缓存，成本日志记录并设 $20 预算上限。</p>
  {figs['ablation']}
  <p><strong>结论</strong>：在 5 折交叉验证下，融合 LLM 语义特征后 AUC 提升 {abl.get('auc_gain', 0):+.4f}、对数损失下降、熵增益 +{abl.get('entropy_gain', 0):.4f} nats——语义特征携带行为特征之外的增量信息，可用于更精细的分层与预测调整（特征维度：行为 {abl.get('n_trad_features', '—')}，语义 {abl.get('n_semantic_features', '—')}）。</p>
</section>

<section id="s5">
  <h2>5　仿真器与真值构建</h2>
  <div class="card-grid">
    <div class="card"><h3>市场主体</h3><p>广告主（档位/预算/出价/质量分/文案语义/转化价值）× 用户（品类兴趣/会话疲劳/负反馈）× 拍卖（一价默认、GSP 可配置、softmax 候选随机化）。</p></div>
    <div class="card"><h3>干扰机制</h3><p>预算竞争、用户广告疲劳、供给替代、广告主流失；策略干预支持竞价门槛、广告条数上限、拍卖规则、预算乘数。</p></div>
    <div class="card"><h3>真值结构</h3><p>对同一策略运行三组全局反事实市场：<code>C</code>（控制）、<code>T0</code>（策略无响应）、<code>T1</code>（策略+广告主响应）。直接效应 = T0−C，间接效应 = T1−T0。</p></div>
  </div>
  <p><strong>机制验证</strong>：预算约束恒成立；无策略时真值效应收敛于 0（无偏性 sanity）；策略变化方向与市场直觉一致（如提高竞价门槛降低总消耗）。这保证后续所有估计器都能对真值计算 bias / RMSE / 覆盖率 / 功效，而非停留在“看起来更准”。</p>
</section>

<section id="s6">
  <h2>6　实验设计：竞争图谱分桶</h2>
  <p>竞争边权重公式：<code>w(i,j) = cosine(语义向量) × (0.5 + 0.5 × 人群 Jaccard) × (0.75 + 0.25 × 预算档位邻近度)</code>；Top-K 边截断后 Louvain 社区检测，超大社区谱聚类递归平衡切分作为随机化单元。</p>
  {figs['graph']}
  {figs['design']}
  {design_tbl}
  <p><strong>结论</strong>：竞争图谱群落分桶把跨组强竞争边占比从 {structured_edge:.3f} 降到约 {graph_edge:.3f}（降幅约 {100 * (1 - graph_edge / structured_edge) if structured_edge else 0:.0f}%），代价是协变量平衡（SMD）适度升高——从源头削减跨组竞争干扰。</p>
</section>

<section id="s7">
  <h2>7　效果评估：准确性证据</h2>
  <h3>7.1 最严苛场景（高干扰 × 高异质性）</h3>
  {worst_tbl}
  <h3>7.2 全部场景平均</h3>
  {overall_tbl}
  {figs['rmse']}
  {figs['bias_rmse']}
  <p><strong>结论</strong>：在干扰与异质性叠加的场景下，传统分桶的估计严重偏置且 Wald 置信区间大面积失准（覆盖率 0.0–0.1）；竞争图谱分桶使 bias 与 RMSE 大幅下降；随机化推断以功效为代价提供校准良好的区间（覆盖率 1.0）；暴露映射在高干扰下区间校准更优。真实业务中应组合使用：图谱分桶控制干扰 + 随机化推断做稳健显著性 + CUPED 削减方差。</p>
</section>

<section id="s8">
  <h2>8　效应剥离与异质性归因</h2>
  <p>内生干扰剥离流程：解析广告主操作日志（调价/改素材/扩定向/退出）→ 类型化事件与幅度 → 响应强度模型校准（真值数据）→ 总效应拆分 <code>总效应 = 直接效应 + 间接效应</code>。</p>
  {est_tbl if loop.get('estimates') else '<p class="muted">闭环样例未生成（无假设可用）。</p>'}
  {figs['attribution']}
  <p><strong>剥离结果（闭环样例）</strong>：总效应 {loop.get('decomposition', {}).get('total_effect', '—')} = 直接效应 {loop.get('decomposition', {}).get('direct_effect', '—')} + 间接效应 {loop.get('decomposition', {}).get('indirect_effect', '—')}；间接效应均值恢复误差 {loop.get('decomposition', {}).get('validation', {}).get('indirect_mean_error', '—')}（理想为 0），直接效应残差主要来自跨组干扰偏置，与第 7 节估计器 bias 一致。</p>
  <p><strong>语义归因</strong>：{loop.get('attribution', '—')}</p>
</section>

<section id="s9">
  <h2>9　反事实均衡模拟</h2>
  <p>策略「{eq.get('policy', '—')}」：LLM 生成广告主类型级响应假设（如中小广告主提升预算 20%），迭代运行含流失机制的均衡；动态模拟收敛：{eq.get('converged', '—')}。灵敏度分析对响应幅度施加 0.5×–1.5× 扰动。</p>
  {eq_tbl}
  {sens_tbl}
  {figs['sensitivity']}
  <p><strong>结论</strong>：忽略广告主主动反馈会系统性误估均衡结果（总消耗与中小广告主存活率均发生显著偏差）；灵敏度带量化了 LLM 行为假设不确定性对生态指标的影响，支持“上线前预筛高风险策略”。</p>
</section>

<section id="s10">
  <h2>10　假设生成与排序</h2>
  <div class="chips">
    {_chip("Top-8 机会召回率", _pct(he.get('recall_at_top_x')), "green")}
    {_chip("优先级 vs 真实效应 Spearman", _fmt(he.get('spearman')))}
    {_chip("50% 价值捕获实验数", f"{he.get('experiments_to_50pct', '—')}（随机 {he.get('random_experiments_to_50pct', '—')}）", "orange")}
  </div>
  {cap_tbl}
  {figs['capture']}
  <h3>优先级排序结果</h3>
  {ranked_tbl}
  <p><strong>结论</strong>：LLM 从工单/负反馈/复盘等非结构化语料提炼假设，按“预期收益 × 置信度 / 风险”排序后，达到 50% 潜在价值捕获仅需 {he.get('experiments_to_50pct', '—')} 个实验（随机基线 {he.get('random_experiments_to_50pct', '—')} 个），显著压缩实验迭代成本。</p>
</section>

<section id="s11">
  <h2>11　闭环演示</h2>
  <p>取排序第一的假设「{loop.get('hypothesis', '—')}」跑通全链路：均衡仿真（风险预筛）→ 竞争图谱分桶（最大 SMD {loop.get('design', {}).get('max_smd', '—')}、跨组强竞争边 {loop.get('design', {}).get('cross_arm_edge_ratio', '—')}）→ 实验估计 → 效应剥离 → 语义归因 → 知识回流。真值直接效应 {loop.get('true_effect', '—')} 与估计结果对照可见：点估计差异反映实验层干扰偏置，归因结论与仿真设定的胜出画像一致。</p>
</section>

<section id="s12">
  <h2>12　复现与工程保障</h2>
  <pre><code># 全流程复现（固定种子）
python -m venv .venv && .venv/bin/pip install -r requirements.txt
.venv/bin/python -m semadexp.cli run-all --scale full
.venv/bin/python -m pytest          # 10 个测试
./scripts/verify.sh                  # 测试 + Notebook 构建 + 冒烟
python scripts/render_html_report.py # 生成本报告</code></pre>
  <p>工程保障：CLI 8 个子命令 · pydantic 配置契约 · 双后端 LLM（离线等价）· 哈希缓存与成本日志 · 固定种子 · CI（GitHub Actions：测试/Notebook/冒烟/产物校验）。示例数据包 <code>data/sample/</code> 无需运行仿真即可查看输入形态。</p>
</section>

<section id="s13">
  <h2>13　局限性与结论</h2>
  <div class="card-grid">
    <div class="card"><h3>语料近似</h3><p>广告文案/操作日志/工单/复盘为受控生成语料；知识库真值来自仿真器而非线上。</p></div>
    <div class="card"><h3>模型简化</h3><p>拍卖与用户模型为简化机制（一价默认/GSP 可配置），未包含多槽位、竞价调优等。</p></div>
    <div class="card"><h3>样本规模</h3><p>场景矩阵重复实验数与知识库规模（60 个历史实验）可进一步放大以获得更紧置信区间。</p></div>
  </div>
  <p><strong>结论</strong>：证据链表明——LLM 语义特征提供增量信息；竞争图谱分桶从源头削减跨组干扰；干扰感知估计与效应剥离显著提升衡量可信度；反事实均衡模拟降低试错成本；假设生成层把迭代从“人工驱动”推向“数据 + AI 驱动”。方法论价值不依赖语料真实性，真实部署需接入线上数据。</p>
</section>

<section id="s14">
  <h2>附录　指标定义</h2>
  <ul>
    <li><strong>bias</strong>：估计量跨重复实验的均值与真值直接效应之差（真值来自全局反事实市场）。</li>
    <li><strong>方差</strong>：跨重复实验的点估计方差（抽样稳定性）。</li>
    <li><strong>RMSE</strong>：√(bias² + 方差)，综合准确性与稳定性。</li>
    <li><strong>覆盖率</strong>：95% 置信区间包含真值的重复实验比例。</li>
    <li><strong>功效</strong>：|估计/标准误| &gt; 1.96 的重复实验比例（真值非零时近似功效）。</li>
    <li><strong>熵增益</strong>：行为特征模型对数损失 − 融合模型对数损失（nats），正值表示语义特征降低预测不确定性。</li>
    <li><strong>跨组强竞争边占比</strong>：权重超过阈值（0.3）的竞争边中跨越处理/对照组的比例。</li>
  </ul>
</section>
</main>

<footer>SemAdExp · 本报告由 <code>scripts/render_html_report.py</code> 从 <code>results/pipeline_summary.json</code> 自动生成 · 固定种子可复现</footer>
"""
    html = _PAGE_HEAD + body + _PAGE_TAIL
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, encoding="utf-8")
    return out_path


_PAGE_HEAD = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>SemAdExp · LLM 语义增强的双边市场实验智能平台 · 可视化技术报告</title>
<style>
:root{--bg:#f6f8fa;--card:#ffffff;--ink:#1f2328;--muted:#59636e;--line:#d8dee4;
--blue:#1f6feb;--green:#1a7f37;--orange:#bc4c00;--red:#d1242f;--nav:#101828;}
*{box-sizing:border-box}
html{scroll-behavior:smooth}
body{margin:0;font-family:"PingFang SC","Hiragino Sans GB","Microsoft YaHei",system-ui,-apple-system,sans-serif;
background:var(--bg);color:var(--ink);line-height:1.75}
code,pre{font-family:"SFMono-Regular",Consolas,"Liberation Mono",monospace;font-size:.88em;
background:#eef1f4;border-radius:4px;padding:1px 5px}
pre{padding:12px 16px;overflow:auto;border:1px solid var(--line)}
.hero{background:linear-gradient(135deg,#0b1f3a 0%,#123c6e 55%,#1f6feb 120%);color:#fff;padding:44px 28px 38px}
.hero-inner{max-width:1180px;margin:0 auto}
.kicker{letter-spacing:.18em;font-size:13px;opacity:.85}
.hero h1{margin:.35rem 0 .4rem;font-size:30px;line-height:1.3}
.subtitle{font-size:15px;opacity:.95;margin:0}
.muted{opacity:.75}
.meta{margin-top:14px;font-size:13px;display:flex;gap:18px;flex-wrap:wrap;opacity:.85}
#toc{position:fixed;top:0;left:0;bottom:0;width:236px;background:var(--nav);color:#dbe4ee;
overflow-y:auto;padding:22px 12px;z-index:10}
.toc-title{font-size:13px;letter-spacing:.15em;opacity:.7;padding:0 10px 10px;text-transform:uppercase}
#toc a{display:block;color:#c9d4e0;text-decoration:none;padding:6px 10px;font-size:13.5px;border-radius:6px}
#toc a:hover{background:#ffffff14;color:#fff}
#toc a.active{background:#1f6feb;color:#fff}
main{margin-left:236px;max-width:1080px;padding:34px 44px 80px}
section{margin-bottom:52px}
h2{font-size:23px;border-bottom:2px solid var(--line);padding-bottom:10px;margin-top:8px}
h2::before{content:"";display:inline-block;width:6px;height:20px;background:var(--blue);margin-right:10px;border-radius:3px}
h3{font-size:17px;color:#0f2a4a;margin-top:26px}
.chips{display:flex;gap:14px;flex-wrap:wrap;margin:18px 0}
.chip{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:12px 16px;min-width:170px}
.chip-label{font-size:12px;color:var(--muted)}
.chip-value{font-size:16px;font-weight:600;margin-top:2px}
.chip-blue .chip-value{color:var(--blue)} .chip-green .chip-value{color:var(--green)}
.chip-orange .chip-value{color:var(--orange)} .chip-red .chip-value{color:var(--red)}
.card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:14px;margin:18px 0}
.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px 18px}
.card h3{margin:0 0 8px;font-size:15px;color:var(--blue)}
.card p{margin:0;font-size:13.5px;color:#3b434c}
table{border-collapse:collapse;width:100%;background:var(--card);font-size:13px;margin:16px 0}
th,td{border:1px solid var(--line);padding:7px 10px;text-align:left}
thead th{background:#eef3f8;position:sticky;top:0}
tbody tr:nth-child(even){background:#f8fafc}
td{font-variant-numeric:tabular-nums}
figure{margin:22px 0;text-align:center}
figcaption{font-size:12.5px;color:var(--muted);margin-top:6px}
.arch{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:22px;margin:18px 0;text-align:center}
.arch-box{display:inline-block;max-width:560px;padding:12px 20px;border-radius:10px;font-size:14px;
border:1px solid var(--line);background:#f4f8fd;color:#123c6e}
.arch-up{border-color:#1a7f37;background:#f2faf4;color:#14532d}
.arch-sim{border-color:#bc4c00;background:#fdf6ee;color:#7a2e00}
.arch-des{border-color:#7c3aed;background:#f7f3fe;color:#4c1d95}
.arch-est{border-color:#1f6feb;background:#eef4ff;color:#0f2a4a}
.arch-arrow{margin:6px 0;color:var(--muted);font-size:16px}
.arch-loop{margin-top:10px;font-size:13px;color:#1a7f37}
footer{margin-left:236px;padding:26px 44px;border-top:1px solid var(--line);color:var(--muted);font-size:13px}
#top{position:fixed;right:22px;bottom:22px;background:var(--blue);color:#fff;border:none;border-radius:50%;
width:42px;height:42px;font-size:18px;cursor:pointer;box-shadow:0 2px 8px #0003;display:none}
@media(max-width:900px){
 #toc{display:none} main{margin-left:0;padding:20px 16px 70px} footer{margin-left:0;padding:16px}
 .hero h1{font-size:23px}
}
@media print{
 #toc{display:none} main{margin:0;padding:10px} footer{margin:0}
 body{background:#fff} section{break-inside:avoid-page}
 figure img{max-width:100%}
}
</style>
</head>
<body>
"""

_PAGE_TAIL = """
<button id="top" title="回到顶部">↑</button>
<script>
const links=[...document.querySelectorAll('#toc a')];
const map=new Map(links.map(a=>[document.querySelector(a.getAttribute('href')),a]));
const obs=new IntersectionObserver(es=>{
  es.forEach(e=>{if(e.isIntersecting){
    links.forEach(a=>a.classList.remove('active'));
    map.get(e.target)?.classList.add('active');
  }});
},{rootMargin:'-15% 0px -70% 0px'});
map.forEach((_,sec)=>obs.observe(sec));
const top=document.getElementById('top');
addEventListener('scroll',()=>{top.style.display=scrollY>600?'block':'none'});
top.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
</script>
</body>
</html>
"""


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--summary", default="results/pipeline_summary.json")
    p.add_argument("--results-dir", default="results")
    p.add_argument("--out", default="docs/semadexp_report.html")
    args = p.parse_args()
    summary_path = Path(args.summary)
    if not summary_path.exists():
        sys.exit(
            f"pipeline_summary.json not found at {summary_path}; run: "
            ".venv/bin/python -m semadexp.cli run-all --scale full"
        )
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    out = _render(summary, Path(args.results_dir), Path(args.out))
    print(f"HTML report -> {out.resolve()} ({out.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
